[package]
name = "ball_tree"
version = "0.3.0"
authors = ["callumjhays <callumjhays@gmail.com>"]

[dependencies]
rayon = "0.5.0"
ndarray = "0.7.1"
simd = "*"

[dev-dependencies]
rand = "0.3"
byteorder = " 0.5"
